from __future__ import annotations

from enum import Enum


class Estado(str, Enum):
    REQUESTED = "REQUESTED"
    REFERENCE_RETRIEVED = "REFERENCE_RETRIEVED"
    STEM_GENERATED = "STEM_GENERATED"
    DISTRACTORS_GENERATED = "DISTRACTORS_GENERATED"
    ITEM_ASSEMBLED = "ITEM_ASSEMBLED"
    BLOCKED_BY_RED_FLAGS = "BLOCKED_BY_RED_FLAGS"
    GENERATION_COMPLETED = "GENERATION_COMPLETED"
    ATTEMPTS_EXHAUSTED = "ATTEMPTS_EXHAUSTED"
    GENERATION_FAILED = "GENERATION_FAILED"


TRANSICOES_PERMITIDAS = {
    Estado.REQUESTED: {Estado.REFERENCE_RETRIEVED, Estado.GENERATION_FAILED},
    Estado.REFERENCE_RETRIEVED: {Estado.STEM_GENERATED, Estado.GENERATION_FAILED},
    Estado.STEM_GENERATED: {Estado.DISTRACTORS_GENERATED, Estado.BLOCKED_BY_RED_FLAGS, Estado.GENERATION_FAILED},
    Estado.DISTRACTORS_GENERATED: {Estado.ITEM_ASSEMBLED, Estado.BLOCKED_BY_RED_FLAGS, Estado.GENERATION_FAILED},
    Estado.ITEM_ASSEMBLED: {Estado.BLOCKED_BY_RED_FLAGS, Estado.GENERATION_COMPLETED, Estado.GENERATION_FAILED},
    Estado.BLOCKED_BY_RED_FLAGS: {
        Estado.REFERENCE_RETRIEVED, Estado.STEM_GENERATED, Estado.DISTRACTORS_GENERATED,
        Estado.ATTEMPTS_EXHAUSTED, Estado.GENERATION_FAILED,
    },
    Estado.GENERATION_COMPLETED: set(),
    Estado.ATTEMPTS_EXHAUSTED: set(),
    Estado.GENERATION_FAILED: set(),
}
